name: 'HELfi Grant premade content'
type: module
core: 8.x
core_version_requirement: '^8 || ^9'
package: HELfi
dependencies:
  - default_content
default_content:
  menu_link_content:
    - 0182c5c9-c99d-4f0d-8311-8a1accabe6fd
    - a1caac9d-8eef-49df-89c7-ddd75c007a4e
    - ada20fc6-a716-42ff-9cc2-3dab6fe51dc3
'interface translation project': grant_applications_content
'interface translation server pattern': modules/contrib/grant_applications_content/helfi_features/grant_applications_content/translations/%language.po
