settings:
  default_submit_button_label: Lähetä
  default_reset_button_label: Palauta
  default_delete_button_label: Poista
  default_wizard_confirmation_label: Complete
  default_preview_next_button_label: Esikatselu
  default_preview_label: Esikatselu
  dialog_options:
    narrow:
      title: Kapea
    wide:
      title: Leveä
element:
  empty_message: '-'
  default_more_title: Lisää
