# Disables automatic triggering
trigger: none

# Opt out of pull request validation
pr: none

pool:
  vmImage: ubuntu-latest

variables:
- group: development

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "18"
    displayName: "Install Node.js"

  - script: |
      cd $(Build.SourcesDirectory)/e2e
      npm ci
    displayName: "npm ci"

  - script: |
      cd $(Build.SourcesDirectory)/e2e
      npx playwright install --with-deps
    displayName: "Install Playwright browsers"

  - script: |
      cd $(Build.SourcesDirectory)/e2e
      npx playwright test public
    displayName: "Run Playwright tests"
    env:
      CI: "true"
      DRUPAL_HOSTNAME: "avustukset.dev.hel.ninja"
