trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

variables:
- group: development


steps:
    - task: NodeTool@0
      inputs:
        versionSpec: "18"
      displayName: "Install Node.js"
    
    - script: npm ci
      displayName: "Install dependencies"
      workingDirectory: $(Build.SourcesDirectory)/e2e

    - script: npx playwright install --with-deps chromium
      displayName: "Install Playwright browsers"
      workingDirectory: $(Build.SourcesDirectory)/e2e

    - script: npx playwright test frontpage
      displayName: "Run Playwright tests"
      workingDirectory: $(Build.SourcesDirectory)/e2e
      env:
        CI: "true"

    - task: PublishTestResults@2
      displayName: 'Publish test results'
      inputs:
        searchFolder: '$(Build.SourcesDirectory)/e2e/test-results'
        testResultsFormat: 'JUnit'
        testResultsFiles: 'e2e-junit-results.xml'
      condition: succeededOrFailed()

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: $(Build.SourcesDirectory)/e2e/playwright-report
        artifact: playwright-report
        publishLocation: 'pipeline'
      condition: succeededOrFailed()
