# Disables automatic triggering
trigger: none

# Opt out of pull request validation
pr: none

pool:
  vmImage: ubuntu-latest

variables:
- group: development

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "18"
    displayName: "Install Node.js"

  - script: |
      cd $(Build.SourcesDirectory)/e2e
      npm ci
    displayName: "npm ci"

  - script: |
      cd $(Build.SourcesDirectory)/e2e
      npx playwright install --with-deps
    displayName: "Install Playwright browsers"

  - script: |
      cd $(Build.SourcesDirectory)/e2e
      npx playwright test frontpage
    displayName: "Run Playwright tests"
    env:
      CI: "true"

  - task: PublishTestResults@2
    displayName: 'Publish test results'
    inputs:
      searchFolder: '$(Build.SourcesDirectory)/e2e/test-results'
      testResultsFormat: 'JUnit'
      testResultsFiles: 'e2e-junit-results.xml'
      mergeTestResults: true
      failTaskOnFailedTests: true
      testRunTitle: 'My End-To-End Tests'
    condition: succeededOrFailed()

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: $(Build.SourcesDirectory)/e2e/playwright-report
      artifact: playwright-report
      publishLocation: 'pipeline'
    condition: succeededOrFailed()
