# Disables automatic triggering
trigger: none

# Opt out of pull request validation
pr: none

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "18"
    displayName: "Install Node.js"

  - script: |
      cd app/e2e
      npm ci
    displayName: "npm ci"

  - script: |
      cd app/e2e
      npx playwright install --with-deps
    displayName: "Install Playwright browsers"

  - script: |
      cd app/e2e
      npx playwright test
    displayName: "Run Playwright tests"
    env:
      CI: "true"
