services:
  e2e:
    container_name: "${COMPOSE_PROJECT_NAME}-e2e"
    image: mcr.microsoft.com/playwright:v1.48.0-jammy
    ipc: host
    network_mode: host
    tty: true
    environment:
      - DISPLAY=${DISPLAY:-""}
    extra_hosts:
      - "$$(DRUPAL_HOSTNAME):127.0.0.1"
    working_dir: /app/e2e
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    profiles:
      - testing
  app:
    environment:
      XDEBUG_CONFIG: "log_level=0"
