<?php

/**
 * @file
 * Primary module hooks for Helsinki-profiili module.
 */

use Drupal\helfi_helsinki_profiili\HelsinkiProfiiliUserData;
use Drupal\helfi_helsinki_profiili\ProfiiliException;
use Drupal\helfi_helsinki_profiili\TokenExpiredException;
use Drupal\user\UserInterface;

/**
 * OpenID Connect post authorize hook.
 *
 * This hook runs after a user has been authorized and claims have been mapped
 * to the user's account.
 *
 * @param \Drupal\user\UserInterface $account
 *   User account object of the authorized user.
 * @param array<mixed> $context
 *   An associative array with context information:
 *   - tokens:         An array of tokens.
 *   - user_data:      An array of user and session data.*
 *   - plugin_id:      The plugin identifier.
 *   - sub:            The remote user identifier.
 */
function helfi_helsinki_profiili_openid_connect_post_authorize(UserInterface $account, array $context): void {
  $session = \Drupal::request()->getSession();
  $session->set('openid_connect_plugin_id', $context["plugin_id"]);
  if (isset($context['tokens']['refresh_token'])) {
    $session->set('openid_connect_refresh_token', $context['tokens']['refresh_token']);
    $session->set('openid_connect_expire', $context['tokens']['expire']);
  }

  if (empty($context["user_data"]["ad_groups"])) {
    $profileDAO = \Drupal::service(HelsinkiProfiiliUserData::class);
    // Fetch HelsinkiProfile data.
    try {
      $data = $profileDAO->getUserProfileData();

      if ($data == NULL) {
        \Drupal::messenger()
          ->addWarning(t('User logged in to Helsinki services, no profile data found.'));
      }
      else {
        \Drupal::messenger()->addStatus(t('User logged in to Helsinki services and data fetched.'));
      }

    }
    catch (TokenExpiredException $e) {
      \Drupal::messenger()->addError(t('User logged in but fetching tokens failed'));
      \Drupal::logger('helfi_helsinki_profiili')
        ->error('API token fetch failed. Error: @error',
          [
            '@error' => $e->getMessage(),
          ]
        );
    }
    catch (ProfiiliException $e) {
      \Drupal::messenger()->addError(t('User logged in to Helsinki services and data fetch failed'));
      \Drupal::logger('helfi_helsinki_profiili')
        ->error('User profile data fetch failed. Error: @error',
          [
            '@error' => $e->getMessage(),
          ]
        );
    }
  }

}
