config_rewrite:
  replace: ['dependencies', 'display.default.cache_metadata.tags', 'display.page_1.cache_metadata.tags']
dependencies:
  config:
    - views.view.avustuslajit
    - views.view.kohderyhmat
  module:
    - entityreference_filter
    - node
    - options
    - user
display:
  default:
    display_options:
      fields:
        revision_uid:
          id: revision_uid
          table: node_revision
          field: revision_uid
          relationship: none
          group_type: group
          admin_label: ''
          entity_type: node
          entity_field: revision_uid
          plugin_id: field
          label: 'Revision user'
          exclude: false
          alter:
            alter_text: false
            text: ''
            make_link: false
            path: ''
            absolute: false
            external: false
            replace_spaces: false
            path_case: none
            trim_whitespace: false
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: false
            max_length: 0
            word_boundary: true
            ellipsis: true
            more_link: false
            more_link_text: ''
            more_link_path: ''
            strip_tags: false
            trim: false
            preserve_tags: ''
            html: false
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: true
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: true
          empty: ''
          hide_empty: false
          empty_zero: false
          hide_alter_empty: true
          click_sort_column: target_id
          type: entity_reference_label
          settings:
            link: true
          group_column: target_id
          group_columns: {  }
          group_rows: true
          delta_limit: 0
          delta_offset: 0
          delta_reversed: false
          delta_first_last: false
          multi_type: separator
          separator: ', '
          field_api_classes: false
      filters:
        field_target_group_target_id_entityreference_filter:
          id: field_target_group_target_id_entityreference_filter
          table: node__field_target_group
          field: field_target_group_target_id_entityreference_filter
          relationship: none
          group_type: group
          admin_label: ''
          plugin_id: entityreference_filter_view_result
          operator: or
          value: null
          group: 1
          exposed: true
          expose:
            operator_id: field_target_group_target_id_entityreference_filter_op
            label: Kohderyhmä
            description: ''
            use_operator: false
            operator: field_target_group_target_id_entityreference_filter_op
            operator_limit_selection: false
            operator_list: {  }
            identifier: field_target_group_target_id_entityreference_filter
            required: false
            remember: false
            multiple: false
            remember_roles:
              authenticated: authenticated
              anonymous: '0'
              json_api_user: '0'
              read_only: '0'
              helsinkiprofiili: '0'
              content_producer_industry: '0'
              content_producer: '0'
              grants_producer: '0'
              ad_user: '0'
              grants_admin: '0'
              admin: '0'
            reduce: false
          is_grouped: false
          group_info:
            label: ''
            description: ''
            identifier: ''
            optional: true
            widget: select
            multiple: false
            remember: false
            default_group: All
            default_group_multiple: {  }
            group_items: {  }
          reduce_duplicates: false
          type: select
          reference_display: 'kohderyhmat:entity_reference_1'
          reference_arguments: ''
          hide_empty_filter: true
        field_hakijatyyppi_value:
          id: field_hakijatyyppi_value
          table: node__field_hakijatyyppi
          field: field_hakijatyyppi_value
          relationship: none
          group_type: group
          admin_label: ''
          plugin_id: list_field
          operator: or
          value: {  }
          group: 1
          exposed: true
          expose:
            operator_id: field_hakijatyyppi_value_op
            label: Hakijatyyppi
            description: ''
            use_operator: false
            operator: field_hakijatyyppi_value_op
            operator_limit_selection: false
            operator_list: {  }
            identifier: field_hakijatyyppi_value
            required: false
            remember: true
            multiple: false
            remember_roles:
              authenticated: authenticated
              anonymous: '0'
              json_api_user: '0'
              read_only: '0'
              helsinkiprofiili: '0'
              content_producer_industry: '0'
              content_producer: '0'
              grants_producer: '0'
              ad_user: '0'
              grants_admin: '0'
              admin: '0'
            reduce: false
          is_grouped: false
          group_info:
            label: ''
            description: ''
            identifier: ''
            optional: true
            widget: select
            multiple: false
            remember: false
            default_group: All
            default_group_multiple: {  }
            group_items: {  }
          reduce_duplicates: false
        field_avustuslaji_target_id_entityreference_filter:
          id: field_avustuslaji_target_id_entityreference_filter
          table: node__field_avustuslaji
          field: field_avustuslaji_target_id_entityreference_filter
          relationship: none
          group_type: group
          admin_label: ''
          plugin_id: entityreference_filter_view_result
          operator: or
          value: null
          group: 1
          exposed: true
          expose:
            operator_id: field_avustuslaji_target_id_entityreference_filter_op
            label: Avustuslaji
            description: ''
            use_operator: false
            operator: field_avustuslaji_target_id_entityreference_filter_op
            operator_limit_selection: false
            operator_list: {  }
            identifier: field_avustuslaji_target_id_entityreference_filter
            required: false
            remember: false
            multiple: false
            remember_roles:
              authenticated: authenticated
              anonymous: '0'
              json_api_user: '0'
              read_only: '0'
              helsinkiprofiili: '0'
              content_producer_industry: '0'
              content_producer: '0'
              grants_producer: '0'
              ad_user: '0'
              grants_admin: '0'
              admin: '0'
            reduce: false
          is_grouped: false
          group_info:
            label: ''
            description: ''
            identifier: ''
            optional: true
            widget: select
            multiple: false
            remember: false
            default_group: All
            default_group_multiple: {  }
            group_items: {  }
          reduce_duplicates: false
          type: select
          reference_display: 'avustuslajit:entity_reference_1'
          reference_arguments: ''
          hide_empty_filter: true
        revision_uid:
          id: revision_uid
          table: node_revision
          field: revision_uid
          relationship: none
          group_type: group
          admin_label: ''
          entity_type: node
          entity_field: revision_uid
          plugin_id: user_name
          operator: in
          value: {  }
          group: 1
          exposed: true
          expose:
            operator_id: revision_uid_op
            label: 'Revision user'
            description: ''
            use_operator: false
            operator: revision_uid_op
            operator_limit_selection: false
            operator_list: {  }
            identifier: revision_uid
            required: false
            remember: false
            multiple: false
            remember_roles:
              authenticated: authenticated
              anonymous: '0'
              json_api_user: '0'
              read_only: '0'
              helsinkiprofiili: '0'
              content_producer_industry: '0'
              content_producer: '0'
              grants_producer_industry: '0'
              grants_producer: '0'
              ad_user: '0'
              grants_admin: '0'
              admin: '0'
              editor: '0'
              super_administrator: '0'
              performance_test_user: '0'
            reduce: false
          is_grouped: false
          group_info:
            label: ''
            description: ''
            identifier: ''
            optional: true
            widget: select
            multiple: false
            remember: false
            default_group: All
            default_group_multiple: {  }
            group_items: {  }
    cache_metadata:
      tags:
        - taxonomy_term_list
  page_1:
    cache_metadata:
      tags:
        - taxonomy_term_list
