/**
 * Statuses Avus2 uses.
 */
export const SubmitStates = {
  CANCELLED: 'CANCELLED',
  DRAFT: 'DRAFT',
  PENDING: 'PENDING',
  PREPARING: 'PREPARING',
  PROCESSING: 'PROCESSING',
  RECEIVED: 'RECEIVED',
  REJECTED: 'REJECTED',
  RESOLVED: 'RESOLVED',
  SUBMITTED: 'SUBMITTED',
};
