/**
 * Statuses Avus2 uses.
 */
export const SubmitStates = {
  CANCELLED: 'CANCELLED',
  CLOSED: 'CLOSED',
  DELETED: 'DELETED',
  DRAFT: 'DRAFT',
  PENDING: 'PENDING',
  PREPARING: 'PREPARING',
  PROCESSING: 'PROCESSING',
  READY: 'READY',
  RECEIVED: 'RECEIVED',
  REJECTED: 'REJECTED',
  RESOLVED: 'RESOLVED',
  SUBMITTED: 'SUBMITTED',
};
