<?php

/**
 * @file
 * Primary module hooks for Front Banner module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

use Drupal\helfi_platform_config\DTO\ParagraphTypeCollection;

/**
 * Implements hook_theme().
 */
function grants_front_banner_theme() {
  return [
    'grants_front_banner' => [
      'variables' => [
        'loggedin' => NULL,
        'fillinfo' => NULL,
        'loginform' => NULL,
        'getgrantsprofile' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_helfi_paragraph_types().
 */
function grants_front_banner_helfi_paragraph_types(): array {
  $entities = [
    'node' => [
      'landing_page' => [
        'field_content' => [
          'front_banner',
        ],
      ],
    ],
  ];

  $enabled = [];
  foreach ($entities as $entityTypeId => $bundles) {
    foreach ($bundles as $bundle => $fields) {
      foreach ($fields as $field => $paragraphTypes) {
        foreach ($paragraphTypes as $paragraphType) {
          $enabled[] = new ParagraphTypeCollection(
            $entityTypeId,
            $bundle,
            $field,
            $paragraphType
          );
        }
      }
    }
  }
  return $enabled;
}
