<?php

/**
 * Implements hook_page_attachments_alter().
 */
function react_form_page_attachments_alter(array &$attachments) {
  // Use the dev library if we're developing locally.

  if (in_array('react_form/react_app', $attachments['#attached']['library']) && file_exists(__DIR__ . '/js/dist_dev')) {
    $index = array_search('react_form/react_app', $attachments['#attached']['library']);
    $attachments['#attached']['library'][$index] = 'react_form/react_app_dev';
  }
}

/**
 * Implements hook_theme().
 */
function react_form_theme($existing, $type, $theme, $path) {
  return [
    'react_form' => [
      'render element' => 'build',
      'variables' => [
        'content' => NULL,
        'webform' => NULL,
      ],
    ],
  ];
}
