administer grants_admin_delete_applications configuration:
  title: 'Administer grants_admin_delete_applications configuration'
  description: 'Optional description.'
  restrict access: true
administer grants_admin_delete_applications_by_transaction_id configuration:
  title: 'Administer grants_admin_delete_applications_by_transaction_id configuration'
  description: 'Optional description.'
  restrict access: true
administer grants_admin_resend_applications configuration:
  title: 'Administer grants_admin_resend_applications configuration'
  description: 'Optional description.'
  restrict access: true
administer grants_admin_submitted_applications configuration:
  title: 'Administer grants_admin_submitted_applications configuration'
  description: 'Optional description.'
  restrict access: true
