grants_admin_applications.submitted_applications_status:
  title: ATV Documents
  route_name: grants_admin_applications.submitted_applications_status
  parent: hdbt_admin_tools.overview
  description: 'Check for applications that are stuck in SUBMITTED state.'
  weight: 10
grants_admin_applications.resend_applications:
  title: Resend Applications / Messages
  route_name: grants_admin_applications.resend_applications
  parent: grants_admin_applications.submitted_applications_status
  description: 'Resend application data through integration.'
  weight: 1
grants_admin_application.delete_applications:
  title: Delete testing applications
  route_name: grants_admin_applications.delete_applications
  parent: grants_admin_applications.submitted_applications_status
  description: 'Delete testing applications.'
  weight: 2
grants_admin_application.delete_applications_by_transaction_id:
  title: Delete testing applications by transaction ID
  route_name: grants_admin_applications.delete_applications_by_transaction_id
  parent: grants_admin_applications.submitted_applications_status
  description: 'Delete testing applications by transaction ID.'
  weight: 3

