name: grants_admin_applications
type: module
description: Provide functionality to delete documents from ATV.
package: Helfi
core: 8.x
core_version_requirement: ^8 || ^9
dependencies:
  - helfi_atv
  - helfi_helsinki_profiili

'interface translation project': grants_admin_applications
'interface translation server pattern': modules/custom/grants_admin_applications/translations/%language.po
