grants_admin_applications.delete_applications:
  path: '/admin/reports/delete-applications'
  defaults:
    _title: 'Delete testing applications'
    _form: 'Drupal\grants_admin_applications\Form\DeleteApplicationsForm'
  requirements:
    _permission: 'administer grants_admin_delete_applications configuration'
grants_admin_applications.delete_applications_by_transaction_id:
  path: '/admin/reports/delete-applications/delete-by-transaction-id'
  defaults:
    _title: 'Delete testing applications by transaction ID'
    _form: 'Drupal\grants_admin_applications\Form\DeleteByTransactionIdForm'
  requirements:
    _permission: 'administer grants_admin_delete_applications configuration'
grants_admin_applications.resend_applications:
  path: '/admin/reports/resend-applications'
  defaults:
    _title: 'Admin: Resend applications'
    _form: 'Drupal\grants_admin_applications\Form\ResendApplicationsForm'
  requirements:
    _permission: 'administer grants_admin_resend_applications configuration'
grants_admin_applications.submitted_applications_status:
  path: '/admin/reports/submitted-applications-status'
  defaults:
    _title: 'Admin: Submitted applications status'
    _form: 'Drupal\grants_admin_applications\Form\SubmittedApplicationsForm'
  requirements:
    _permission: 'administer grants_admin_submitted_applications configuration'
