grants_admin_applications.admin_applications_uuid:
  path: '//admin/reports/admin-applications-uuid'
  defaults:
    _title: 'Delete testing applications'
    _form: 'Drupal\grants_admin_applications\Form\AdminApplicationsByUuidForm'
  requirements:
    _permission: 'administer grants_admin_applications configuration'
grants_admin_applications.admin_applications_buid:
  path: '//admin/reports/admin-applications-buid'
  defaults:
    _title: 'Admin applications by Business id'
    _form: 'Drupal\grants_admin_applications\Form\AdminApplicationsByBusinessIdForm'
  requirements:
    _permission: 'administer grants_admin_applications configuration'
grants_admin_applications.resend_applications:
  path: '/admin/reports/resend-applications'
  defaults:
    _title: 'Admin: Resend applications'
    _form: 'Drupal\grants_admin_applications\Form\ResendApplicationsForm'
  requirements:
    _permission: 'administer grants_admin_resend_applications configuration'
grants_admin_applications.submitted_applications_status:
  path: '/admin/reports/submitted-applications-status'
  defaults:
    _title: 'Admin: Submitted applications status'
    _form: 'Drupal\grants_admin_applications\Form\SubmittedApplicationsForm'
  requirements:
    _permission: 'administer grants_admin_submitted_applications configuration'
