<?php

/**
 * @file
 * Primary module hooks for Form Tool Audit Log module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\helfi_api_base\AuditLog\AuditLogService;
use Drupal\helfi_api_base\AuditLog\Event\AuditLogEvent;

/**
 * Implements hook_user_login().
 */
function grants_audit_log_user_login(AccountInterface $account): void {
  \Drupal::service(AuditLogService::class)->logOperation(new AuditLogEvent(
    operation: "DRUPAL_LOGIN",
    message: "SUCCESS",
    target: [
      "id" => $account->id(),
      "type" => "USER",
      "name" => "User Login",
    ],
  ));
}

/**
 * Implements hook_user_logout().
 */
function grants_audit_log_user_logout(AccountInterface $account): void {
  \Drupal::service(AuditLogService::class)->logOperation(new AuditLogEvent(
    operation: "DRUPAL_LOGOUT",
    message: "SUCCESS",
    target: [
      "id" => $account->id(),
      "type" => "USER",
      "name" => "User Logout",
    ],
  ));
}

/**
 * Implements hook_entity_view().
 */
function grants_audit_log_entity_view(array &$build, EntityInterface $entity): void {

  // Only trigger event for webform nodes and submissions.
  if ($entity->bundle() == "webform") {
    \Drupal::service(AuditLogService::class)->logOperation(new AuditLogEvent(
      operation: "READ",
      message: "SUCCESS",
      target: [
        "id" => $entity->id(),
        "type" => "WEBFORM",
        "name" => "Form Viewed",
      ],
    ));
  }
}

/**
 * Implements hook_entity_insert().
 */
function grants_audit_log_entity_insert(EntityInterface $entity): void {

  // Trigger event only for users, webform nodes and webform submissions.
  if ($entity->getEntityTypeId() == "user" || ($entity->getEntityTypeId() == "node" && $entity->bundle() == "webform")) {
    \Drupal::service(AuditLogService::class)->logOperation(new AuditLogEvent(
      operation: "CREATE",
      message: "SUCCESS",
      target: [
        "id" => $entity->id(),
        "type" => mb_strtoupper($entity->bundle()),
        "name" => "Entity Created",
      ],
    ));
  }
}

/**
 * Implements hook_entity_delete().
 */
function grants_audit_log_entity_delete(EntityInterface $entity): void {

  // Trigger event only for users, webform nodes and webform submissions.
  if ($entity->getEntityTypeId() == "user" || ($entity->getEntityTypeId() == "node" && $entity->bundle() == "webform")) {
    \Drupal::service(AuditLogService::class)->logOperation(new AuditLogEvent(
      operation: "DELETE",
      message: "SUCCESS",
      target: [
        "id" => $entity->id(),
        "type" => mb_strtoupper($entity->bundle()),
        "name" => "Entity Deleted",
      ],
    ));
  }
}

/**
 * Implements hook_entity_update().
 */
function grants_audit_log__entity_update(EntityInterface $entity): void {

  // Trigger event only for users, webform nodes and webform submissions.
  if ($entity->getEntityTypeId() == "user" || ($entity->getEntityTypeId() == "node" && $entity->bundle() == "webform")) {
    \Drupal::service(AuditLogService::class)->logOperation(new AuditLogEvent(
      operation: "UPDATE",
      message: "SUCCESS",
      target: [
        "id" => $entity->id(),
        "type" => mb_strtoupper($entity->bundle()),
        "name" => "Entity Updated",
      ],
    ));
  }
}
