grants_handler.settings:
  type: config_object
  label: 'Grants handler settings'
  mapping:
    statusStrings:
      type: sequence
      label: 'Status strings by language'
      sequence:
        type: sequence
        label: 'Language status strings'
        sequence:
          type: string
          label: 'Language status label'

webform.handler.grants_handler:
  type: mapping
  label: 'Grants handler settings'
  mapping:
    debug:
      type: boolean
      label: 'Enable debug mode'
    endpoint:
      type: string
      label: 'Custom endpoint'
    message:
      type: string
      label: 'Custom message'

block.settings.grants_handler_service_page_auth_block:
  type: block_settings
  label: 'Service Page Block block'
  mapping:
    foo:
      type: string
      label: Foo
