webform.handler.example:
  type: mapping
  label: Example
  mapping:
    message:
      label: Message
      type: string
    debug:
      type: boolean
      label: 'Enable debugging'
grants_handler.statusStrings:
  type: config_object
  label: 'Status strings'
  mapping:
    message:
      type: text
      label: 'Message'