services:
  _defaults:
    autowire: true
    autoconfigure: true

  logger.channel.grants_application:
    parent: logger.channel_base
    arguments: ['grants_application']

  Drupal\grants_application\Form\FormSettingsService:
    arguments:
      - '@entity_type.manager'
      - '@extension.list.module'
      - '@language_manager'
  Drupal\grants_application\Form\ApplicationNumberService: ~
  Drupal\grants_application\Form\ApplicationMetadataForm: ~

  Drupal\grants_application\User\UserInformationService: ~

  Drupal\grants_application\Atv\HelfiAtvService: ~

  Drupal\grants_application\Avus2Mapper: ~

  Drupal\grants_application\Avus2Integration: ~

  Drupal\grants_application\Form\FormValidator: ~
