<?php

/**
 * @file
 * Module hooks.
 */

use Drupal\Core\Field\FieldStorageDefinitionInterface;
use Drupal\Core\Entity\FieldableEntityInterface;

/**
 * Implements hook_theme().
 */
function grants_application_theme(): array {
  return [
    'forms_app' => [
      'variables' => [
        'application_number' => NULL,
      ],
    ],
  ];
}

/**
 * Register routes to apply Gin’s content edit form layout.
 *
 * @return array
 *   An array of route names.
 *
 * @see GinContentFormHelper->isContentForm()
 */
function grants_application_gin_content_form_routes(): array {
  // Apply gin theme to application metadata forms.
  return [
    'entity.application_metadata.add_form',
    'entity.application_metadata.edit_form',
  ];
}

/**
 * Allowed values callback for the Application type field.
 *
 * @param \Drupal\Core\Field\FieldStorageDefinitionInterface $definition
 *   The field storage definition.
 * @param \Drupal\Core\Entity\FieldableEntityInterface|null $entity
 *   The entity context if known.
 *
 * @return array
 *   An array of key => label pairs, where the key is the machine name of the
 *   application type and the label is the human-readable name.
 */
function grants_application_application_type_allowed_values(
  FieldStorageDefinitionInterface $definition,
  ?FieldableEntityInterface $entity,
): array {
  $config = \Drupal::configFactory()->getEditable('grants_application.settings');
  return array_map(
    fn($type) => $type['labels']['fi'],
    $config->get('application_types') ?: []
  );
}

/**
 * Allowed values callback for the Application industry field.
 *
 * @param \Drupal\Core\Field\FieldStorageDefinitionInterface $definition
 *   The field storage definition.
 * @param \Drupal\Core\Entity\FieldableEntityInterface|null $entity
 *   The entity context if known.
 *
 * @return array
 *   An array of key => label pairs, where the key is the machine name of the
 *   application type and the label is the human-readable name.
 */
function grants_application_application_industry_allowed_values(
  FieldStorageDefinitionInterface $definition,
  ?FieldableEntityInterface $entity,
): array {
  $config = \Drupal::configFactory()->getEditable('grants_application.settings');
  return $config->get('application_industries') ?? [];
}

/**
 * Allowed values callback for the Application types field.
 *
 * @param \Drupal\Core\Field\FieldStorageDefinitionInterface $definition
 *   The field storage definition.
 * @param \Drupal\Core\Entity\FieldableEntityInterface|null $entity
 *   The entity context if known.
 *
 * @return array
 *   An array of key => label pairs, where the key is the machine name of the
 *   application type and the label is the human-readable name.
 */
function grants_application_applicant_types_allowed_values(
  FieldStorageDefinitionInterface $definition,
  ?FieldableEntityInterface $entity,
): array {
  $config = \Drupal::configFactory()->getEditable('grants_application.settings');
  return $config->get('applicant_types') ?? [];
}

/**
 * Allowed values callback for the Application types field.
 *
 * @param \Drupal\Core\Field\FieldStorageDefinitionInterface $definition
 *   The field storage definition.
 * @param \Drupal\Core\Entity\FieldableEntityInterface|null $entity
 *   The entity context if known.
 *
 * @return array
 *   An array of key => label pairs, where the key is the machine name of the
 *   application type and the label is the human-readable name.
 */
function grants_application_application_subvention_types_allowed_values(
  FieldStorageDefinitionInterface $definition,
  ?FieldableEntityInterface $entity,
): array {
  $config = \Drupal::configFactory()->getEditable('grants_application.settings');
  return $config->get('subvention_types') ?? [];
}

/**
 * Allowed values callback for the Application acting years field.
 *
 * @param \Drupal\Core\Field\FieldStorageDefinitionInterface $definition
 *   The field storage definition.
 * @param \Drupal\Core\Entity\FieldableEntityInterface|null $entity
 *   The entity context if known.
 *
 * @return array
 *   An array of key => label pairs, where the key is the machine name of the
 *   application type and the label is the human-readable name.
 */
function grants_application_application_acting_years_allowed_values(
  FieldStorageDefinitionInterface $definition,
  ?FieldableEntityInterface $entity,
): array {
  $current_year = (int) date('Y');
  $years = range($current_year, $current_year + 10);
  return array_combine($years, $years);
}
