services:
  _defaults:
    autowire: true
    autoconfigure: true

  logger.channel.grants_application:
    parent: logger.channel_base
    arguments: ['grants_application']

  Drupal\grants_application\Form\FormSettingsService: ~
  Drupal\grants_application\Form\ApplicationNumberService: ~

  Drupal\grants_application\User\UserInformationService: ~

  Drupal\grants_application\Atv\HelfiAtvService: ~

