<?php

use Drupal\config_ignore\ConfigIgnoreConfig;

/**
 * Implements hook_config_ignore_ignored_alter().
 *
 * Allow creating new webforms when importing.
 * Prevent from editing or deleting when importing or exporting.
 */
function grants_webform_import_config_ignore_ignored_alter(ConfigIgnoreConfig $ignored): void {
  foreach(['import', 'export'] as $operation) {
    $list = $ignored->getList($operation, 'create');
    $list = array_filter($list, fn($line) => $line !== 'webform.webform.*');
    $ignored->setList($operation, 'create', $list);
  }
}
