_core:
  default_config_hash: pYO-DH32fm7GYMJrNx5syvfx2n-5s88kvuddFKXC758
enabled: true
timeout: 1800
max_timeout: 172800
padding: 60
logout_regardless_of_activity: false
no_individual_logout_threshold: true
role_logout: false
role_logout_max: false
redirect_url: /
no_dialog: false
message: 'Your session is about to expire. Do you want to reset it?'
inactivity_message: 'You have been logged out due to inactivity.'
inactivity_message_type: status
modal_width: 450
enforce_admin: false
jstimer_format: '%hours%:%mins%:%secs%'
jstimer_js_load_option: false
use_alt_logout_method: false
use_watchdog: true
dialog_title: 'Hel.fi Avustusasiointi Alert'
disable_buttons: false
yes_button: ''
no_button: ''
whitelisted_ip_addresses: ''
cookie_secure: true
cookie_samesite: Lax
cookie_httponly: true
