verbose: true
types:
  node:
    '*': '*'
  paragraphs_library_item:
    '*': '*'
  taxonomy_term:
    '*': '*'
  tpr_service:
    '*': '*'
  tpr_unit:
    '*': '*'
  application_submission:
    '*': '*'
types_translation_lock: {  }
form_op_lock:
  node:
    mode: 0
    values: {  }
  paragraphs_library_item:
    mode: 0
    values: {  }
  taxonomy_term:
    mode: 0
    values: {  }
  tpr_service:
    mode: 0
    values: {  }
  tpr_unit:
    mode: 0
    values: {  }
  application_submission:
    mode: null
    values: {  }
timeout: 7200
