_core:
  default_config_hash: yOPH6uEZYRHbg2OFP-bze0jGr06fI-Gr_66W-vA8Faw
report-only:
  enable: false
  directives: {  }
  reporting:
    plugin: none
enforce:
  enable: true
  directives:
    default-src:
      base: self
    img-src:
      base: any
    script-src:
      base: self
      flags:
        - report-sample
        - unsafe-inline
        - unsafe-eval
        - wasm-unsafe-eval
    style-src:
      base: self
      flags:
        - report-sample
        - unsafe-inline
    base-uri:
      base: none
    frame-ancestors:
      base: self
  reporting:
    plugin: raven
