statusStrings:
  en:
    DRAFT: Draft
    SENT: Sent
    SUBMITTED: Submitted
    RECEIVED: Received
    PENDING: Pending
    PROCESSING: Processing
    READY: Ready
    DONE: Done
    REJECTED: Rejected
    DELETED: Deleted
    CANCELED: Canceled
    CANCELLED: Canceled
    CLOSED: Closed
  fi:
    DRAFT: Luonnos
    SENT: Lähetetty
    SUBMITTED: 'Lähetetty - odotetaan vahvistusta'
    RECEIVED: Vastaanotettu
    PENDING: Odottaa
    PROCESSING: Käsittelyssä
    READY: Valmiina
    DONE: Käsitelty
    REJECTED: Hylätty
    DELETED: Poistettu
    CANCELED: Peruttu
    CANCELLED: Peruttu
    CLOSED: Ratkaistu
  sv:
    DRAFT: Utkast
    SENT: Skickas
    SUBMITTED: Lämnats
    RECEIVED: Mottagits
    PENDING: I väntan på
    PROCESSING: Behandlas
    READY: Redo
    DONE: Avgjort
    REJECTED: Avvisade
    DELETED: Raderade
    CANCELED: Annulerad
    CANCELLED: Inställt
    CLOSED: Stängd
langcode: fi
