statusStrings:
  en:
    DRAFT: Draft
    SENT: Sent
    SUBMITTED: Submitted
    RECEIVED: Received
    PREPARING: 'In Preparation'
    PENDING: Pending
    PROCESSING: Processing
    READY: Ready
    DONE: Processed
    REJECTED: Rejected
    DELETED: Deleted
    CANCELED: Cancelled
    CANCELLED: Cancelled
    CLOSED: Closed
    RESOLVED: Resolved
  fi:
    DRAFT: Luonnos
    SENT: Lähetetty
    SUBMITTED: 'Lähetetty - odotetaan vahvistusta'
    RECEIVED: Vastaanotettu
    PREPARING: Valmistelussa
    PENDING: Odottaa
    PROCESSING: Käsittelyssä
    READY: Valmiina
    DONE: Ratkaistu
    REJECTED: Hylätty
    DELETED: Poistettu
    CANCELED: Peruttu
    CANCELLED: Peruttu
    CLOSED: Suljettu
    RESOLVED: Valmis
  sv:
    DRAFT: Utkast
    SENT: Skickad
    SUBMITTED: Lämnats
    RECEIVED: Mottagen
    PREPARING: Förbereds
    PENDING: 'I väntan på'
    PROCESSING: Behandlas
    READY: Redo
    DONE: Behandlad
    REJECTED: Avvisade
    DELETED: Raderade
    CANCELED: Annullerad
    CANCELLED: Annullerad
    CLOSED: Stängd
    RESOLVED: Färdig
langcode: fi
