third_party_options:
  application_industries:
    KYMP: KYMP
    SOTE: SOTE
    KANSLIA: KANSLIA
    PEL: PEL
    KUVA: KUVA
    KASKO: KASKO
  applicant_types:
    registered_community: 'Rekisteröity yhdistys'
    unregistered_community: 'Rekisteröitymätön yhteisö tai ryhmä'
    private_person: Yksityishenkilö
  application_types:
    29:
      id: ECONOMICGRANTAPPLICATION
      code: YLEIS
      dataDefinition:
        definitionClass: Drupal\grants_metadata\TypedData\Definition\YleisavustusHakemusDefinition
        definitionId: grants_metadata_yleisavustushakemus
      labels:
        fi: 'Kaupunginhallitus, yleisavustushakemus'
        en: 'City Board, general grant application'
        sv: 'Stadsstyrelsen, allmän bidragsansökan'
    47:
      id: KUVATOIM
      code: KUVATOIM
      dataDefinition:
        definitionClass: Drupal\grants_metadata\TypedData\Definition\KuvaToimintaDefinition
        definitionId: grants_metadata_kuvatoiminta
      labels:
        fi: 'Taide- ja kulttuuriavustukset: toiminta-avustukset'
        en: 'Arts and culture grants: Operational grants'
        sv: 'Understöd för konst och kultur: Verksamhetsunderstöd'
    48:
      id: KUVAPROJ
      code: KUVAPROJ
      dataDefinition:
        definitionClass: Drupal\grants_metadata\TypedData\Definition\KuvaProjektiDefinition
        definitionId: grants_metadata_kaskoyleis
      labels:
        fi: 'Taide- ja kulttuuriavustukset: projektiavustukset'
        en: 'Arts and culture grants: Project grants'
        sv: 'Understöd för konst och kultur: Projektstöd'
    49:
      id: KUVAKEHA
      code: KUVAKEHA
      dataDefinition:
        definitionClass: Drupal\grants_metadata\TypedData\Definition\KuvaKehaDefinition
        definitionId: grants_metadata_kuvakeha
      labels:
        fi: 'Kulttuurin kehittämisavustukset'
        en: 'Development grants for culture'
        sv: 'Utvecklingsstöd för kultur'
    50:
      id: KUVAPERUS
      code: KUVAPERUS
      dataDefinition:
        definitionClass: Drupal\grants_metadata\TypedData\Definition\KuvaPerusDefinition
        definitionId: grants_metadata_kuvaperus
      labels:
        fi: 'Taiteen perusopetuksen avustukset'
        en: 'Basic arts education grants'
        sv: 'Stöd för grundläggande konstundervisning'
    51:
      id: KASKOYLEIS
      code: KASKOYLEIS
      dataDefinition:
        definitionClass: Drupal\grants_metadata\TypedData\Definition\KaskoYleisavustusDefinition
        definitionId: grants_metadata_kaskoyleis
      labels:
        fi: 'Kasvatus ja koulutus, yleisavustushakemus'
        en: 'Education, general grant application'
        sv: 'Fostran och utbildning, allmän bidragsansökan'
    52:
      id: KASKOIPTOIM
      code: KASKOIPTOIM
      dataDefinition:
        definitionClass: Drupal\grants_metadata\TypedData\Definition\KaskoToimintaDefinition
        definitionId: grants_metadata_kaskotoiminta
      labels:
        fi: 'Kasvatus ja koulutus, toiminta-avustushakemus koululaisten iltapäivätoiminnan järjestäjille'
        en: 'Education, grant application for organisers of afternoon activities for school children'
        sv: 'Fostran och utbildning, ansökan om verksamhetsbidrag för organisatörer av eftermiddagsverksamhet för skolbarn'
    53:
      id: KASKOIPLISA
      code: KASKOIPLISA
      dataDefinition:
        definitionClass: Drupal\grants_metadata\TypedData\Definition\KaskoIltapaivaLisaDefinition
        definitionId: grants_metadata_kaskoiplisa
      labels:
        fi: 'Kasvatus ja koulutus, iltapäivätoiminnan harkinnanvarainen lisäavustushakemus'
        en: 'Education, supplementary discretionary grant application for afternoon activities'
        sv: 'Fostran och utbildning, ansökan om extra bidrag enligt behovsprövning för eftermiddagsverksamhet'
    54:
      id: KANSLIATYO
      code: KANSLIATYO
      dataDefinition:
        definitionClass: Drupal\grants_metadata\TypedData\Definition\TyollisyysavustusHakemusDefinition
        definitionId: grants_metadata_tyollisyysavustushakemus
      labels:
        fi: 'Kaupunginkanslia, työllisyysavustushakemus'
        en: 'City Executive Office, employment grant application'
        sv: 'Stadskansliet, ansökan om sysselsättningsunderstöd'
    56:
      id: LIIKUNTAYLEIS
      code: LIIKUNTAYLEIS
      dataDefinition:
        definitionClass: \Drupal\grants_metadata\TypedData\Definition\LiikuntaYleisDefinition
        definitionId: grants_metadata_liikuntayleis
      labels:
        fi: 'Liikunta, yleisavustushakemus'
        en: 'Sports, general grant application'
        sv: 'Idrott, allmän bidragsansökan'
    57:
      id: LIIKUNTALAITOS
      code: LIIKUNTALAITOS
      dataDefinition:
        definitionClass: Drupal\grants_metadata\TypedData\Definition\LiikuntaLaitosDefinition
        definitionId: grants_metadata_liikuntalaitos
      labels:
        fi: 'Liikunta, laitos- ja säätiöavustukset'
        en: 'Sports, grants for institutions and foundations'
        sv: 'Idrott,  bidrag för anstalter och stiftelser'
    58:
      id: LIIKUNTASUUNNISTUS
      code: LIIKUNTASUUNNISTUS
      dataDefinition:
        definitionClass: Drupal\grants_metadata\TypedData\Definition\LiikuntaSuunnistusDefinition
        definitionId: grants_metadata_liikuntasuunnistus
      labels:
        fi: 'Liikunta, suunnistuskartta-avustushakemus'
        en: 'Sports, grant application for orienteering maps'
        sv: 'Idrott, ansökan om bidrag för orienteringskarta'
    59:
      id: LIIKUNTATAPAHTUMA
      code: LIIKUNTATAPAHTUMA
      dataDefinition:
        definitionClass: Drupal\grants_metadata\TypedData\Definition\LiikuntaTapahtumaDefinition
        definitionId: grants_metadata_liikuntatapahtuma
      labels:
        fi: 'Liikunta, tapahtuma-avustushakemus'
        en: 'Sports, grant application for events'
        sv: 'Idrott, ansökan om evenemangsbidrag'
    60:
      id: LIIKUNTATILANKAYTTO
      code: LIIKUNTATILANKAYTTO
      dataDefinition:
        definitionClass: Drupal\grants_metadata\TypedData\Definition\LiikuntaTilankayttoDefinition
        definitionId: grants_metadata_liikuntatilankaytto
      labels:
        fi: 'Liikunta, toiminta- ja tilankäyttöavustushakemus'
        en: 'Sports, grant application for activities and use of space'
        sv: 'Idrott, ansökan om bidrag för verksamhet och lokaler'
    61:
      id: YMPARISTOYLEIS
      code: YMPARISTOYLEIS
      dataDefinition:
        definitionClass: Drupal\grants_metadata\TypedData\Definition\YmparistoYleisDefinition
        definitionId: grants_metadata_ymparisto_yleis
      labels:
        fi: 'Ympäristöpalvelut, yleisavustushakemus'
        en: 'Environmental services, general grant application'
        sv: 'Miljötjänster, allmän bidragsansökan'
    62:
      id: NUORPROJ
      code: NUORPROJ
      dataDefinition:
        definitionClass: Drupal\grants_metadata\TypedData\Definition\NuorisoProjektiDefinition
        definitionId: grants_metadata_nuorisoprojekti
      labels:
        fi: 'Nuorisotoimi, projektiavustushakemus'
        en: 'Project grants for youth activities'
        sv: 'Ungdomsverksamhet, projektunderstöd'
    63:
      id: NUORTOIMPALKKA
      code: NUORTOIMPALKKA
      dataDefinition:
        definitionClass: Drupal\grants_metadata\TypedData\Definition\NuorisoToimintaDefinition
        definitionId: grants_metadata_nuorisotoiminta
      labels:
        fi: 'Nuorisopalvelu, toiminta- ja palkkausavustushakemus'
        en: 'Youth service, operations and employment grant application'
        sv: 'Ungdomstjänst, ansökan om verksamhets- och anställningsbidrag'
    64:
      id: ASUKASPIEN
      code: ASUKASPIEN
      dataDefinition:
        definitionClass: Drupal\grants_metadata\TypedData\Definition\AsukaPienaDefinition
        definitionId: grants_metadata_asukaspien
      labels:
        fi: 'Asukasosallisuus, pienavustushakemus'
        en: 'Citizen Participation, small grant application'
        sv: 'Invånardelaktighet, ansökan om små bidrag'
    65:
      id: NUORLOMALEIR
      code: NUORLOMALEIR
      dataDefinition:
        definitionClass: Drupal\grants_metadata\TypedData\Definition\NuorisoLomaDefinition
        definitionId: grants_metadata_nuorisoloma
      labels:
        fi: 'Nuorisotoimi, loma-aikojen leiriavustushakemus'
        en: 'Holiday camp grants for youth activities'
        sv: 'Ungdomsverksamhet, lägerunderstöd under skollovstider'
    66:
      id: NUORTOIMPALKENNAKKO
      code: NUORTOIMPALKENNAKKO
      dataDefinition:
        definitionClass: Drupal\grants_metadata\TypedData\Definition\NuorisoToimintaEnnakkoDefinition
        definitionId: grants_metadata_nuortoimennakko
      labels:
        fi: 'Nuorisotoimi, toiminta- ja palkkausavustusennakkohakemus'
        en: 'Youth service, operations and employment grant advance application'
        sv: 'Ungdomstjänst, förskottsansökan om verksamhets- och anställningsbidrag'
    67:
      id: ASUKASYLEISTOIM
      code: ASUKASYLEISTOIM
      dataDefinition:
        definitionClass: Drupal\grants_metadata\TypedData\Definition\AsukasYleisToimDefinition
        definitionId: grants_metadata_asukasyleistoim
      labels:
        fi: 'Asukasosallisuus, yleis- ja toiminta-avustushakemus'
        en: 'Citizen Participation, general and operational grant application'
        sv: 'Invånardelaktighet, ansökan om allmänna och verksamhetsbidrag'
    68:
      id: HYVINYLEIS
      code: HYVINYLEIS
      dataDefinition:
        definitionClass: Drupal\grants_metadata\TypedData\Definition\HyvinYleisDefinition
        definitionId: grants_metadata_hyvinyleis
      labels:
        fi: 'Hyvinvoinnin ja terveyden edistämisen sekä sosiaali-, terveys- ja pelastustoimen yleisavustushakemus'
        en: 'General grants for welfare and health promotion, social welfare and health care and rescue services'
        sv: 'Allmänt understöd inom främjandet av välfärd och hälsa och social- och hälsovården samt räddningsväsendet'
    69:
      id: LEIRISELVITYS
      code: LEIRISELVITYS
      dataDefinition:
        definitionClass: Drupal\grants_metadata\TypedData\Definition\NuorisoLeiriSelvitysDefinition
        definitionId: grants_metadata_nuorisoleiriselvitys
      labels:
        fi: 'Nuorisopalvelu, loma-aikojen leiriavustusselvitys'
        en: 'Youth service, camp grant report for holiday periods'
        sv: 'Ungdomstjänst, utredning över lägerbidrag under semestertiden'
    70:
      id: KUVAERILLIS
      code: KUVAERILLIS
      dataDefinition:
        definitionClass: Drupal\grants_metadata\TypedData\Definition\KuvaErillisDefinition
        definitionId: grants_metadata_kuvaerillis
      labels:
        fi: 'KuvaErillis FI'
        en: 'KuvaErillis EN'
        sv: 'KuvaErillis SV'
  application_statuses:
    DRAFT: DRAFT
    SUBMITTED: SUBMITTED
    RECEIVED: RECEIVED
    PREPARING: PREPARING
    PENDING: PENDING
    PROCESSING: PROCESSING
    CANCELLED: CANCELLED
    RESOLVED: RESOLVED
  subvention_types:
    1: 'Operating grant'
    2: 'Wage subsidy'
    4: 'Project grant'
    5: 'Rent subsidy'
    6: 'General grant'
    7: 'Education grant for unemployed'
    8: 'Interests and installments'
    9: Other
    11: 'Transport subsidy'
    12: 'Camp grant'
    13: 'Exemption from payments compensation'
    14: 'Extra grant'
    15: 'Navigation map grant'
    17: 'Grant for operations development'
    29: 'Development grant / The Helsinki Model'
    31: 'Start grant'
    32: 'Facility usage grant'
    34: 'Basic arts education'
    35: 'Early childhood education'
    36: 'Liberal adult education'
    37: 'Event grant'
    38: 'Small grant'
    39: 'Immigrant integration grant'
    40: 'Culture and leisure: application for subsidy'
    41: 'Institution and foundation grants'
    42: 'Grant for other associations promoting physical activity'
    43: 'Targeted sports grant'
    44: 'Development grant'
    45: 'Development grant for the Helsinki Model'
    46: 'Development grant for basic arts education'
    47: 'Special grant for culture 1'
    48: 'Special grant for culture 2'
    49: 'Special grant for youth activities 1'
    50: 'Special grant for youth activities 2'
    51: 'Special grant for sports 1'
    52: 'Special grant for sports 2'
    53: 'Special grant for culture and leisure 1'
    54: 'Special grant for culture and leisure 2'
langcode: en
config_import_ignore:
  - 53
  - 51
  - 48
  - 56
  - 50
  - 59
  - 29
  - 65
  - 62
  - 54
  - 52
  - 61
  - 68
  - 57
  - 58
  - 60
  - 65
  - 67
overridden_configuration:
  -
    53:
      grants_metadata:
        applicationOpen: '2023-06-16T08:30:52'
        applicationClose: '2029-08-19T08:36:07'
        disableCopying: 0
  -
    51:
      grants_metadata:
        applicationOpen: '2023-04-03T08:00:00'
        applicationClose: '2029-10-06T16:00:00'
        disableCopying: 0
  -
    48:
      grants_metadata:
        applicationOpen: '2022-10-02T11:08:26'
        applicationClose: '2029-11-30T11:19:00'
        disableCopying: 0
  -
    47:
      grants_metadata:
        applicationOpen: '2022-10-02T11:08:26'
        applicationClose: '2029-07-31T11:19:00'
        disableCopying: 0
  -
    59:
      grants_metadata:
        applicationOpen: '2023-02-18T09:28:04'
        applicationClose: '2029-11-24T09:28:11'
        disableCopying: 0
  -
    56:
      grants_metadata:
        applicationOpen: '2022-10-03T11:08:26'
        applicationClose: '2029-07-30T11:19:00'
        disableCopying: 0
  -
    66:
      grants_metadata:
        applicationOpen: '2022-10-02T11:08:26'
        applicationClose: '2029-07-31T11:19:00'
        disableCopying: 0
  -
    62:
      grants_metadata:
        applicationOpen: '2022-10-02T11:08:26'
        applicationClose: '2029-12-22T11:19:00'
        disableCopying: 0
  -
    65:
      grants_metadata:
        applicationOpen: '2022-10-03T11:08:26'
        applicationClose: '2029-08-30T11:19:00'
        disableCopying: 0
  -
    49:
      grants_metadata:
        applicationOpen: '2022-10-02T11:08:26'
        applicationClose: '2029-07-30T11:19:00'
        disableCopying: 0
  -
    50:
      grants_metadata:
        applicationOpen: '2022-10-02T11:08:26'
        applicationClose: '2029-07-31T11:19:00'
        disableCopying: 0
  -
    29:
      grants_metadata:
        applicationOpen: '2022-10-03T11:08:26'
        applicationClose: '2029-07-30T11:19:00'
        disableCopying: 0
  -
    60:
      grants_metadata:
        applicationOpen: '2022-10-03T11:08:26'
        applicationClose: '2029-07-30T11:19:00'
        disableCopying: 0
  -
    61:
      grants_metadata:
        applicationOpen: '2022-10-03T11:08:26'
        applicationClose: '2029-07-30T11:19:00'
        disableCopying: 0
  -
    58:
      grants_metadata:
        applicationOpen: '2022-10-03T11:08:26'
        applicationClose: '2029-07-30T11:19:00'
        disableCopying: 0
  -
    52:
      grants_metadata:
        applicationOpen: '2022-10-03T11:08:26'
        applicationClose: '2029-07-30T11:19:00'
        disableCopying: 0
  -
    54:
      grants_metadata:
        applicationOpen: '2022-10-03T11:08:26'
        applicationClose: '2029-07-30T11:19:00'
        disableCopying: 0
  -
    68:
      grants_metadata:
        applicationOpen: '2022-10-03T11:08:26'
        applicationClose: '2029-07-30T11:19:00'
        disableCopying: 0
  -
    69:
      grants_metadata:
        applicationOpen: '2022-10-03T11:08:26'
        applicationClose: '2029-07-30T11:19:00'
        disableCopying: 0
  -
    57:
      grants_metadata:
        applicationOpen: '2022-10-03T11:08:26'
        applicationClose: '2029-07-30T11:19:00'
        disableCopying: 0
  -
    53:
      grants_metadata:
        applicationOpen: '2022-10-03T11:08:26'
        applicationClose: '2029-07-30T11:19:00'
        disableCopying: 0
  -
    64:
      grants_metadata:
        applicationOpen: '2022-10-03T11:08:26'
        applicationClose: '2029-07-30T11:19:00'
        disableCopying: 0
  -
    63:
      grants_metadata:
        applicationOpen: '2022-10-03T11:08:26'
        applicationClose: '2029-07-30T11:19:00'
        disableCopying: 0
  -
    67:
      grants_metadata:
        applicationOpen: '2024-01-03T11:08:26'
        applicationClose: '2029-07-30T11:19:00'
        disableCopying: 0
