third_party_options:
  application_industries:
    KYMP: KYMP
    SOTE: SOTE
    KANSLIA: KANSLIA
    PEL: PEL
    KUVA: KUVA
    KASKO: KASKO
  applicant_types:
    registered_community: 'Rekisteröity yhdistys'
    unregistered_community: 'Rekisteröitymätön yhteisö tai ryhmä'
    private_person: Yksityishenkilö
  application_types:
    29:
      id: ECONOMICGRANTAPPLICATION
      code: YLEIS
      dataDefinition:
        definitionClass: Drupal\grants_metadata\TypedData\Definition\YleisavustusHakemusDefinition
        definitionId: grants_metadata_yleisavustushakemus
      labels:
        fi: 'Kaupunginhallitus, yleisavustushakemus'
        en: 'City Board, general grant application'
        sv: 'Stadsstyrelsen, allmän bidragsansökan'
    48:
      id: KUVAPROJ
      code: KUVAPROJ
      dataDefinition:
        definitionClass: Drupal\grants_metadata\TypedData\Definition\KuvaProjektiDefinition
        definitionId: grants_metadata_kaskoyleis
      labels:
        fi: 'Taide- ja kulttuuriavustukset: projektiavustukset'
        en: 'Arts and culture grants: Project grants'
        sv: 'Understöd för konst och kultur: Projektstöd'
    49:
      id: KUVAKEHA
      code: KUVAKEHA
      dataDefinition:
        definitionClass: Drupal\grants_metadata\TypedData\Definition\KuvaKehaDefinition
        definitionId: grants_metadata_kaskoyleis
      labels:
        fi: 'Kulttuurin kehittämisavustukset'
        en: 'Development grants for culture'
        sv: 'Utvecklingsstöd för kultur'
    51:
      id: KASKOYLEIS
      code: KASKOYLEIS
      dataDefinition:
        definitionClass: Drupal\grants_metadata\TypedData\Definition\KaskoYleisavustusDefinition
        definitionId: grants_metadata_kaskoyleis
      labels:
        fi: 'Kasvatus ja koulutus, yleisavustushakemus'
        en: 'Education, general grant application'
        sv: 'Fostran och utbildning, allmän bidragsansökan'
    47:
      id: KUVATOIM
      code: KUVATOIM
      dataDefinition:
        definitionClass: Drupal\grants_metadata\TypedData\Definition\KuvaToimintaDefinition
        definitionId: grants_metadata_kuvatoiminta
      labels:
        fi: 'Taide- ja kulttuuriavustukset: toiminta-avustukset'
        en: 'Arts and culture grants: Operational grants'
        sv: 'Understöd för konst och kultur: Verksamhetsunderstöd'
    54:
      id: KANSLIATYO
      code: KANSLIATYO
      dataDefinition:
        definitionClass: Drupal\grants_metadata\TypedData\Definition\TyollisyysavustusHakemusDefinition
        definitionId: grants_metadata_tyollisyysavustushakemus
      labels:
        fi: 'Kaupunginkanslia, työllisyysavustushakemus'
        en: 'City Executive Office, employment grant application'
        sv: 'Stadskansliet, ansökan om sysselsättningsunderstöd'
    59:
      id: LIIKUNTATAPAHTUMA
      code: LIIKUNTATAPAHTUMA
      dataDefinition:
        definitionClass: Drupal\grants_metadata\TypedData\Definition\LiikuntaTapahtumaDefinition
        definitionId: grants_metadata_liikuntatapahtuma
      labels:
        fi: 'Liikunta, tapahtuma-avustushakemus'
        en: 'Sports, grant application for events'
        sv: 'Idrott, ansökan om evenemangsbidrag'
    66:
      id: NUORTOIMPALKENNAKKO
      code: NUORTOIMPALKENNAKKO
      dataDefinition:
        definitionClass: Drupal\grants_metadata\TypedData\Definition\NuorisoToimintaEnnakkoDefinition
        definitionId: grants_metadata_nuortoimennakko
      labels:
        fi: 'Nuorisotoiminta, toiminta- ja palkkausavustus ennakkohakemus'
        en: 'Youth service, operations and employment grant advance application'
        sv: 'Ungdomstjänst, förskottsansökan om verksamhets- och anställningsbidrag'
    56:
      id: LIIKUNTAYLEIS
      code: LIIKUNTAYLEIS
      dataDefinition:
        definitionClass: \Drupal\grants_metadata\TypedData\Definition\LiikuntaYleisDefinition
        definitionId: grants_metadata_liikuntayleis
      labels:
        fi: 'Liikunta, yleisavustushakemus'
        en: 'Sports, general grant application'
        sv: 'Idrott, allmän bidragsansökan'
    50:
      id: KUVAPERUS
      code: KUVAPERUS
      dataDefinition:
        definitionClass: Drupal\grants_metadata\TypedData\Definition\KuvaPerusDefinition
        definitionId: grants_metadata_kuvaperus
      labels:
        fi: 'Taiteen perusopetuksen avustukset'
        en: 'Basic arts education grants'
        sv: 'Stöd för grundläggande konstundervisning'
    62:
      id: NUORPROJ
      code: NUORPROJ
      dataDefinition:
        definitionClass: Drupal\grants_metadata\TypedData\Definition\NuorisoProjektiDefinition
        definitionId: grants_metadata_nuorisoprojekti
      labels:
        fi: 'Nuorisotoimi, projektiavustushakemus'
        en: 'Project grants for youth activities'
        sv: 'Ungdomsverksamhet, projektunderstöd'
    53:
      id: KASKOIPLISA
      code: KASKOIPLISA
      dataDefinition:
        definitionClass: Drupal\grants_metadata\TypedData\Definition\KaskoIltapaivaLisaDefinition
        definitionId: grants_metadata_kaskoiplisa
      labels:
        fi: 'Kasvatus ja koulutus, iltapäivätoiminnan harkinnanvarainen lisäavustushakemus'
        en: 'Education, supplementary discretionary grant application for afternoon activities'
        sv: 'Fostran och utbildning, ansökan om extra bidrag enligt behovsprövning för eftermiddagsverksamhet'
    65:
      id: NUORLOMALEIR
      code: NUORLOMALEIR
      dataDefinition:
        definitionClass: Drupal\grants_metadata\TypedData\Definition\NuorisoLomaDefinition
        definitionId: grants_metadata_nuorisoloma
      labels:
        fi: 'Nuorisotoiminta, loma-aikojen leiriavustushakemus'
        en: 'Holiday camp grants for youth activities'
        sv: 'Ungdomsverksamhet, lägerunderstöd under skollovstider'
    64:
      id: ASUKASPIEN
      code: ASUKASPIEN
      dataDefinition:
        definitionClass: Drupal\grants_metadata\TypedData\Definition\AsukaPienaDefinition
        definitionId: grants_metadata_asukaspien
      labels:
        fi: 'Asukasosallisuus, pienavustushakemus'
        en: 'Citizen Participation, small grant application'
        sv: 'Invånardelaktighet, ansökan om små bidrag'
    58:
      id: LIIKUNTASUUNNISTUS
      code: LIIKUNTASUUNNISTUS
      dataDefinition:
        definitionClass: Drupal\grants_metadata\TypedData\Definition\LiikuntaSuunnistusDefinition
        definitionId: grants_metadata_liikuntasuunnistus
      labels:
        fi: 'Liikunta, Suunnistuskartta-avustushakemus'
        en: 'Sports, grant application for orienteering maps'
        sv: 'Idrott, ansökan om bidrag för orienteringskarta'
    60:
      id: LIIKUNTATILANKAYTTO
      code: LIIKUNTATILANKAYTTO
      dataDefinition:
        definitionClass: Drupal\grants_metadata\TypedData\Definition\LiikuntaTilankayttoDefinition
        definitionId: grants_metadata_liikuntatilankaytto
      labels:
        fi: 'Liikunta, toiminta- ja tilankäyttöavustushakemus'
        en: 'Sports, grant application for activities and use of space'
        sv: 'Idrott, ansökan om bidrag för verksamhet och lokaler'
    57:
      id: LIIKUNTALAITOS
      code: LIIKUNTALAITOS
      dataDefinition:
        definitionClass: Drupal\grants_metadata\TypedData\Definition\LiikuntaLaitosDefinition
        definitionId: grants_metadata_liikuntalaitos
      labels:
        fi: 'Liikunta, laitos- ja säätiöavustukset'
        en: 'Sports, grants for institutions and foundations'
        sv: 'Idrott,  bidrag för anstalter och stiftelser'
    67:
      id: ASUKASYLEISTOIM
      code: ASUKASYLEISTOIM
      dataDefinition:
        definitionClass: Drupal\grants_metadata\TypedData\Definition\KansliatyoDefinition
        definitionId: grants_metadata_kansliatyo
      labels:
        fi: 'Asukasosallisuus: yleis- ja toiminta-avustushakemus'
        en: 'Citizen Participation, general and operational grant application'
        sv: 'Invånardelaktighet, ansökan om allmänna och verksamhetsbidrag'
    61:
      id: YMPARISTOYLEIS
      code: YMPARISTOYLEIS
      dataDefinition:
        definitionClass: Drupal\grants_metadata\TypedData\Definition\YmparistoYleisDefinition
        definitionId: grants_metadata_ymparisto_yleis
      labels:
        fi: 'Ympäristöpalvelut: Yleisavustushakemus'
        en: 'Environmental services, general grant application'
        sv: 'Miljötjänster, allmän bidragsansökan'
  application_statuses:
    DRAFT: DRAFT
    SENT: SENT
    SUBMITTED: SUBMITTED
    RECEIVED: RECEIVED
    PENDING: PENDING
    PROCESSING: PROCESSING
    READY: READY
    DONE: DONE
    REJECTED: REJECTED
    DELETED: DELETED
    CANCELED: CANCELED
    CANCELLED: CANCELLED
    CLOSED: CLOSED
  subvention_types:
    1: 'Operating grant'
    2: 'Wage subsidy'
    4: 'Project grant'
    5: 'Rent subsidy'
    6: 'General grant'
    7: 'Education grant for unemployed'
    8: 'Interests and installments'
    9: Other
    11: 'Transport subsidy'
    12: 'Camp grant'
    13: 'Exemption from payments compensation'
    14: 'Extra grant'
    15: 'Navigation map grant'
    17: 'Grant for operations development'
    29: 'Capacity buildning grant / The Helsinki Model'
    31: 'Start grant'
    32: 'Subsidy for use of space'
    34: 'Basic art education'
    35: 'Early childhood education'
    36: 'Liberal adult education'
    37: 'Event grant'
    38: 'Small grant'
    39: 'Immigrant integration grant'
    40: 'Culture and leisure: application for subsidy'
    41: 'Institution and foundation grants'
    42: 'Grant for other associations promoting physical activity'
    43: 'Targeted sports grant'
    44: 'Capacity building grant'
    45: 'Capacity building grant / The Helsinki Model'
    46: 'Capacity building grant for basic art education'
langcode: en
config_import_ignore:
  - 53
  - 51
  - 48
  - 56
  - 50
overridden_configuration:
  - 53:
      grants_metadata:
        applicationOpen: '2023-06-16T08:30:52'
        applicationClose: '2029-08-19T08:36:07'
        disableCopying: 0
  - 51:
      grants_metadata:
        applicationOpen: '2023-04-03T08:00:00'
        applicationClose: '2029-10-06T16:00:00'
        disableCopying: 0
  - 48:
      grants_metadata:
        applicationOpen: '2022-10-02T11:08:26'
        applicationClose: '2029-11-30T11:19:00'
        disableCopying: 0
  - 47:
      grants_metadata:
        applicationOpen: '2022-10-02T11:08:26'
        applicationClose: '2029-07-31T11:19:00'
        disableCopying: 0
  - 59:
      grants_metadata:
        applicationOpen: '2023-02-18T09:28:04'
        applicationClose: '2029-11-24T09:28:11'
        disableCopying: 0
  - 56:
      grants_metadata:
        applicationOpen: '2022-10-03T11:08:26'
        applicationClose: '2029-07-30T11:19:00'
        disableCopying: 0
  - 66:
      grants_metadata:
        applicationOpen: '2022-10-02T11:08:26'
        applicationClose: '2029-07-31T11:19:00'
        disableCopying: 0
  - 62:
      grants_metadata:
        applicationOpen: '2022-10-02T11:08:26'
        applicationClose: '2029-12-22T11:19:00'
        disableCopying: 0
  - 65:
      grants_metadata:
        applicationOpen: '2022-10-03T11:08:26'
        applicationClose: '2029-08-30T11:19:00'
        disableCopying: 0
  - 49:
      grants_metadata:
        applicationOpen: '2022-10-02T11:08:26'
        applicationClose: '2029-07-30T11:19:00'
        disableCopying: 0
  - 50:
      grants_metadata:
        applicationOpen: '2022-10-02T11:08:26'
        applicationClose: '2029-07-31T11:19:00'
        disableCopying: 0
  - 29:
      grants_metadata:
        applicationOpen: '2022-10-03T11:08:26'
        applicationClose: '2029-07-30T11:19:00'
        disableCopying: 0
  - 60:
      grants_metadata:
        applicationOpen: '2022-10-03T11:08:26'
        applicationClose: '2029-07-30T11:19:00'
        disableCopying: 0
  - 61:
      grants_metadata:
        applicationOpen: '2022-10-03T11:08:26'
        applicationClose: '2029-07-30T11:19:00'
        disableCopying: 0
