statusStrings:
  en:
    DRAFT: Draft
    SENT: Sent
    SUBMITTED: Submitted
    RECEIVED: Received
    PREPARING: 'In Preparations'
    PENDING: Pending
    PROCESSING: 'In Progress'
    READY: Ready
    RESOLVED: Resolved
    DONE: Solved
    REJECTED: Rejected
    DELETED: Deleted
    CANCELED: Canceled
    CANCELLED: Canceled
    CLOSED: Closed
  fi:
    DRAFT: Luonnos
    SENT: Lähetetty
    SUBMITTED: 'Lähetetty - odotetaan vahvistusta'
    RECEIVED: Vastaanotettu
    PREPARING: Valmistelussa
    PENDING: Odottaa
    PROCESSING: Käsittelyssä
    READY: Valmiina
    RESOLVED: Ratkaistu
    DONE: Ratkaistu
    REJECTED: Hylätty
    DELETED: Poistettu
    CANCELED: Peruttu
    CANCELLED: Peruttu
    CLOSED: Suljettu
  sv:
    DRAFT: Utkast
    SENT: Skickas
    SUBMITTED: Lämnats
    RECEIVED: Mottagits
    PREPARING: 'I förberedelse'
    PENDING: 'I väntan på'
    PROCESSING: Behandlas
    READY: Redo
    RESOLVED: Löst
    DONE: Avgjort
    REJECTED: Avvisade
    DELETED: Raderade
    CANCELED: Annulerad
    CANCELLED: Inställt
    CLOSED: Stängd
langcode: fi
