_core:
  default_config_hash: AOXdYmkvKEWQ90i8bbStpi07jONjN29ny1BcgITQFSM
langcode: en
site_settings:
  default_icon: abstract-1
  theme_color: engel
  koro: basic
  path_to_json: /themes/contrib/hdbt/src/icons/editor-selectable-icons.json
footer_settings:
  footer_color: dark
