<?php

declare(strict_types=1);

namespace Drupal\Tests\grants_application\Kernel\Entity;

use Drupal\block_content\Entity\BlockContent;
use Drupal\grants_application\Controller\ApplicationController;
use Drupal\grants_application\Entity\ApplicationSubmission;
use Drupal\Tests\grants_application\Kernel\KernelTestBase;
use Drupal\Tests\user\Traits\UserCreationTrait;
use Drupal\user\Entity\Role;
use Symfony\Component\HttpFoundation\RedirectResponse;

/**
 * @coversDefaultClass \Drupal\grants_application\Entity\ApplicationSubmission
 *
 * @group grants_application
 */
final class ApplicationSubmissionLockTest extends KernelTestBase {

  use UserCreationTrait;

  protected static $modules = ['content_lock', 'block_content', 'node', 'helfi_tunnistamo'];

  protected $strictConfigSchema = FALSE;


  private string $applicationNumber = 'KERNELT-058-0123456';

  private ApplicationController $controller;

  private ApplicationSubmission $applicationSubmission;

  /**
   * {@inheritdoc}
   */
  protected function setUp(): void {
    parent::setUp();

    $locale_tables = [
      'locales_source',
      'locales_target',
      'locales_location',
    ];
    $this->installSchema('locale', $locale_tables);
    $this->installSchema('webform', 'webform');
    $this->installSchema('user', ['users_data']);

    $this->installConfig(['content_lock', 'block_content', 'grants_handler', 'language', 'helfi_tunnistamo']);

    $this->installEntitySchema('block_content');
    $this->installEntitySchema('application_submission');

    $config = $this->config('content_lock.settings')
      ->set('types.application_submission', ['*' => '*'])
      ->set('verbose', TRUE);
    $config->save();

    $this->installSchema('content_lock', 'content_lock');

    /** @var Drupal\user\Entity\Role $role */
    $role = Role::load('helsinkiprofiili');
    $user = $this->createUser($role->getPermissions(), 'testuser');
    $this->setUpCurrentUser(['id' => $user->id()]);

    BlockContent::create([
      'id' => 1,
      'revision_id' => 1,
      'type' => 'terms_block',
      'uuid' => '89cff493-8888-436f-80d6-231698dad338',
      'langcode' => 'fi',
    ])->save();

    $entity = \Drupal::entityTypeManager()->getStorage('block_content')->load(1);
    $entity->set('body', 'asdasd')->set('field_link_title', 'Link title goes here')->save();

    $this->applicationSubmission = ApplicationSubmission::create([
      'id' => 1,
      'uuid' => 'aaaaaaaa-1111-2222-3333-bbbcccdddeeee',
      'document_id' => 'bbbbbbbb-4444-5555-6666-fffggghhhiiijjj',
      'sub' => 'abcdefg-1234-5678-9012-hijklmnopqro',
      'business_id' => 'qwertyui-1234-1234-1234-qweasdzxcrty',
      'draft' => TRUE,
      'langcode' => 'fi',
      'application_type_id' => 58,
      'application_number' => $this->applicationNumber,
      'created' => '1765430954',
      'changed' => '1765430954',
    ]);
    $this->applicationSubmission->save();

    $this->controller = ApplicationController::create($this->container);
  }

  protected function tearDown(): void
  {
    parent::tearDown(); // TODO: Change the autogenerated stub
  }

  /**
   * Test that content lock is set properly.
   */
  public function testApplicationLock(): void {
    // First round should set the lock.
    $this->controller->formsApp('58', $this->applicationNumber, TRUE);

    $contentLock = $this->container->get('content_lock');
    $this->assertTrue(
      $contentLock->isLockedBy(
        $this->applicationSubmission,
        '*',
        (int) $this->container->get('current_user')->id()
      )
    );

    // Second round should allow entry for same user.
    $result = $this->controller->formsApp('58', $this->applicationNumber, TRUE);
    $this->assertIsArray($result);

    // Another user should be redirected.
    $role = Role::load('helsinkiprofiili');
    $user = $this->createUser($role->getPermissions(), 'testuser2');
    $this->setUpCurrentUser(['id' => $user->id()]);

    $result = $this->controller->formsApp('58', $this->applicationNumber, TRUE);
    $this->assertTrue($result instanceof RedirectResponse);
  }

}
