dialog_title: 'Automatisk utloggningsvarning'
yes_button: Fortsätta
no_button: 'Logga ut'
message: 'Du är på väg att loggas ut på grund av inaktivitet.'
inactivity_message: 'Du har blivit utloggad på grund av inaktivitet.'
