#! /bin/bash

# Copy files to a different location
cp -r conf/cmi/webform.webform.* public/modules/custom/grants_handler/config/install/

# Add the copied files to the index
git add public/modules/custom/grants_handler/config/install

# Check if there are any changes
if ! git diff --staged --quiet --exit-code; then
  git commit -m "Automatic: Synced changed webform configurations to grants_handler/config/install"
  echo '####################################################################'
  echo '# Created automatic sync commit for changed webform configurations #'
  echo '####################################################################'
fi

# Return 0 to allow the original commit to proceed
exit 0
